//
// BadRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BadRequest: Codable {

    public var timestamp: String
    public var status: Double
    public var error: String
    public var path: String

    public init(timestamp: String, status: Double, error: String, path: String) {
        self.timestamp = timestamp
        self.status = status
        self.error = error
        self.path = path
    }


}

