//
// CaffWithoutCommentsWrapper.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CaffWithoutCommentsWrapper: Codable {

    public var caffs: [CaffWithoutComments]

    public init(caffs: [CaffWithoutComments]) {
        self.caffs = caffs
    }


}

