//
// CaffBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CaffBody: Codable {

    public var title: String
    public var creatorId: Int?
    public var keywords: [String]
    public var base64Caff: String

    public init(title: String, creatorId: Int?, keywords: [String], base64Caff: String) {
        self.title = title
        self.creatorId = creatorId
        self.keywords = keywords
        self.base64Caff = base64Caff
    }


}

