//
// Caff.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Caff: Codable {

    public var title: String
    public var _id: Int
    public var creatorId: Int?
    public var keywords: [String]
    public var base64Preview: String
    public var comments: [CommentResponse]

    public init(title: String, _id: Int, creatorId: Int?, keywords: [String], base64Preview: String, comments: [CommentResponse]) {
        self.title = title
        self._id = _id
        self.creatorId = creatorId
        self.keywords = keywords
        self.base64Preview = base64Preview
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _id = "id"
        case creatorId
        case keywords
        case base64Preview
        case comments
    }


}

