//
// CaffWrapper.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CaffWrapper: Codable {

    public var caffs: [Caff]

    public init(caffs: [Caff]) {
        self.caffs = caffs
    }


}

