//
// FullCaff.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FullCaff: Codable {

    public var base64Caff: String

    public init(base64Caff: String) {
        self.base64Caff = base64Caff
    }


}

