//
// LoginRegistrationBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginRegistrationBody: Codable {

    public var password: String
    public var name: String

    public init(password: String, name: String) {
        self.password = password
        self.name = name
    }


}

