//
// RegistrationModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegistrationModel: Codable {

    public var name: String
    public var password: String

    public init(name: String, password: String) {
        self.name = name
        self.password = password
    }


}

